### ISSUE TITLE
imageOverlay._image.parentElement.replaceChild

### ISSUE THREAD

**Issue by robert1c** [gregallensworth/L.TileLayer.Cordova#10]
Hi

when I use "L.TileLayer.Cordova"  and  function imageOverlay._image.parentElement.replaceChild "_image" is not defined.
Do I something wrong. Please help me.

r.

**Comment by gregallensworth** [comment]
Can you clarify this? I'm not following what you're trying to accomplish, nor how a ImageOverlay class comes into the question.
