### ISSUE TITLE
iOS9?

### ISSUE THREAD

**Issue by adamcoulombe** [gregallensworth/L.TileLayer.Cordova#11]
Hey I'm having trouble getting tiles to load.. I'm on iOS9, im just wondering if there is an issue?

**Comment by gregallensworth** [comment]
It works for me on iOS 9. That's where I do the bulk of my development.
Without more details, I can't say a lot more offhand.

On Thu, Jan 14, 2016 at 9:49 AM, Adam Coulombe notifications@github.com
wrote:

> Hey I'm having trouble getting tiles to load.. I'm on iOS9, im just
> wondering if there is an issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gregallensworth/L.TileLayer.Cordova/issues/11.

## 

Greg Allensworth
BS  A+  Linux+  Network+  Security+  Server+  ZCE-PHP5

**Comment by adamcoulombe** [comment]
I found the issue I was having but it wasn't iOS related.

It appears mapbox changed their api so the example app in the repo doesn't load the  tile images.

**Comment by gregallensworth** [comment]
Thanks for noticing that! I have updated the example and the docs, to use OSM's tiles which work well for a demo and which aren't from a commercial service likely to change their API soon.
