### ISSUE TITLE
Chrome - L.TileLayer.Cordova: device does not support requestFileSystem

### ISSUE THREAD

**Issue by robindierckx** [gregallensworth/L.TileLayer.Cordova#12]
Hello,

I am quite new to ionic & cordova, so appologies if I am saying something stupid.
I installed the relevant cordova plugins, but I cannot get rid ov the following error message when running ionic serve on chrome : 

`L.TileLayer.Cordova: device does not support requestFileSystem`

window.requestFileSystem seem to be undefined.

First test seems to show it works on tablet when running ionic run android.

Am I doing something wrong, or is the plugin not working in chrome?

Thanks.

**Comment by gregallensworth** [comment]
Chrome is not the same as Cordova. It does not support the File API in the same way, though does support a different implementation of it.

Historically, I found that protoyping in Chrome is only viable for the visual prototyping phase. The moment we need real-device code such as File API, it's time to switch to real devices. Its emulation mode, and even some of the old emulators such as ripple, really do little more than downsize the screen and introduce a GPS emulator.

**Comment by robindierckx** [comment]
Ok great, thanks for your clarifying answer.
As I am indeed prototyping in Chrome, it would be very useful to make the plugin non-blocking in chrome: i.e., it shows the leaflet map normally, but without doing the caching. I don't know how complicated it is to adapt this.
