### ISSUE TITLE
Use cached tiles online?

### ISSUE THREAD

**Issue by jboothe** [gregallensworth/L.TileLayer.Cordova#13]
Will your plugin use cached tiles while online. For instance, user is online and pans to an area that they previously visited. Will the cached tiles be pulled or are cached tiles only used when offline? 

Thanks.

**Comment by gregallensworth** [comment]
See the _goOffline()_ and _goOnline()_ functions. These toggle the cache between online mode and offline mode, in which it uses _exclusively_ the online/network tiles or else the stored/offline tiles.

It would be up to your own application logic to detect a loss of network connectivity, detect a sudden increase in tile-loading failures, etc. and then toggle to online/offline mode accordingly.
