### ISSUE TITLE
Error import in INtel XDK

### ISSUE THREAD

**Issue by danicarla** [gregallensworth/L.TileLayer.Cordova#22]
Hi guys...
I use IntelXDK but when I try to import I get the following error: "Cannot find plugin.xml"

Does anyone know how to solve it?

![erro1](https://user-images.githubusercontent.com/13678818/27970950-3a259876-6327-11e7-9c5a-686773c57ae5.jpg)

![erro2](https://user-images.githubusercontent.com/13678818/27970952-3e5de650-6327-11e7-8c00-32b5f784eaeb.jpg)

**Comment by gregallensworth** [comment]
Looks like XDK is looking for a `plugin.xml` file in the repository, containing metadata.

https://software.intel.com/en-us/xdk/docs/add-manage-project-plugins

https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html

I'll read up and see what I can come up with.

**Comment by gregallensworth** [comment]
Hey there. Reading over this, I think that a `plugin.xml` would not be relevant here, and that you're trying to use L.TileLayer.Cordova as a Cordova plugin. It is not a Cordova plugin, but a JavaScript library for Leaflet.

You would include it using a SCRIPT tag same as you do with Leaflet. Same as with Leaflet, put the `leaflet-tilelayer-cordova.js` file in your `www` flder and add something like this in the HTML file:
```
<script src="js/leaflet-tilelayer-cordova.js"></script>
```

Then try JS code similar to that in the README file:  https://github.com/gregallensworth/L.TileLayer.Cordova

**Comment by danicarla** [comment]
You were right .. I was thinking it was a plugin!
Thanks for your help!
