### ISSUE TITLE
TMS based tiles are wrong

### ISSUE THREAD

**Issue by karigarweb** [gregallensworth/L.TileLayer.Cordova#25]
As TMS standard force y value to be caculated in negative, this plugin is producing wrong tile number for y axis.

**Comment by gregallensworth** [comment]
Good catch. This was not tested with `tms: true` L.TileLayers, so I missed that.

I'll see what I can do...

**Comment by karigarweb** [comment]
On getY, following code can convert to TMS based tile number:
`y = Math.pow(2, z) - y - 1;`

Than swap t1_y & t2_y as the values are going to be inverse.

**Comment by gregallensworth** [comment]
@karigarweb  Could you please check out the `issue25-tms` branch and give it a try? It looks good to me, but I'm away from my work computer for a few days so can't test it thoroughly.

The patch specifically is here:  https://github.com/gregallensworth/L.TileLayer.Cordova/blob/a87c01ea160ebd34c6ecd12bf1d88ee5aa70cd5e/src/leaflet-tilelayer-cordova.js#L175-L184

**Comment by gregallensworth** [comment]
@karigarweb Did you get to check out the `issue25-tms` version, to confirm that it's working?

**Comment by karigarweb** [comment]
Yes, everything is working like a charm! Thank you
