### ISSUE TITLE
Add TypeScript type definitions 

### ISSUE THREAD

**Issue by rwev** [gregallensworth/L.TileLayer.Cordova#27]
Here's a good start for [leaflet-tilelayer-cordova.d.ts](https://gist.github.com/rwev/73c8a1679e0d031eb8d4cc4afa0c3ef9)

If this is something you'd like to do, let me know if a pull request is preferred.

**Comment by gregallensworth** [comment]
Thank you very much, Ryan. I have added this to L.TileLayer.Cordova
