### ISSUE TITLE
can we pre populate with certain area map and distribute along with map

### ISSUE THREAD

**Issue by Alphatiger** [gregallensworth/L.TileLayer.Cordova#8]
We are trying to serve maps offline

Two options

1) pre populate with required png's
2) file transfer required maps as one single file do further procsessing and serve maps

**Comment by gregallensworth** [comment]
This would be beyond the scope of L.TileLayer.Cordova, and would be application code and app distribution questions.

If you can pre-generate every PNG and bundle it into your Cordova app's _www/_ folder, then you wouldn't need L.TileLayer.Cordova at all. Simply configure your L.TileLayer to load from _www/tiles/{z}/{x}/{y}/png_ and there would be no need for network access at all. This would mean a large app download, but very good performance and no network access.

Downloading a ZIP file and unpacking it into an application folder, would be beyond the scope of L.TileLayer.Cordova. But offhand, I'd say that if the app unpacks the ZIP under the tiles folder, and if the tiles are named with the same convention, this should work.
